#!/usr/bin/env python

from BMovieConstants import *
from WeightedTuple import WeightedTuple


conceptWordLists = {
    nameConceptNeutral : WeightedTuple( [
        "Destiny",          1,
        "Eternity",         1,
        "Everything",       1,
        "Evolution",        1,
        "Forever",          1,
        "Gold",             1,
        "Gravity",          1,
        "History",          1,
        "Infinity",         2,
        "Lore",             1,
        "Magic",            2,
        "Mystery",          2,
        "Science",          2,
        "Space",            3,
        "Technology",       1,
        "The Universe",     1,
        "Time",             1,
    ] ),

    nameConceptPositive : WeightedTuple( [
        "Beauty",           1,
        "Enlightenment",    1,
        "Glory",            1,
        "Good",             1,
        "Hope",             1,
        "Life",             1,
        "Light",            1,
        "Love",             1,
        "Pride",            1,
        "Prosperity",       1,
        "Redemption",       1,
        "Resurrection",     1,
        "Revelation",       1,
        "Righteousness",    1,
        "Sanity",           1,
        "Spirituality",     1,
        "Triumph",          1,
        "Truth",            1,
        "Victory",          1,
    ] ),

    nameConceptNegative : WeightedTuple ( [
        "Adversity",        1,
        "Confusion",        1,
        "Danger",           2,
        "Darkness",         1,
        "Death",            1,
        "Deceit",           1,
        "Defeat",           1,
        "Delusion",         1,
        "Despair",          1,
        "Doom",             2,
        "Evil",             1,
        "Famine",           1,
        "Fear",             1,
        "Hate",             1,
        "Horror",           1,
        "Infamy",           1,
        "Madness",          1,
        "Oblivion",         2,
        "Oppression",       1,
        "Pain",             1,
        "Pestilence",       1,
        "Poverty",          1,
        "Prejudice",        1,
        "Rage",             1,
        "Shame",            1,
        "Sin",              1,
        "Terror",           1,
        "The Occult",       2,
    ] ),

    nameDirection : WeightedTuple( [
        "Deep South",       1,
        "East",             2,
        "Far East",         1,
        "Far North",        1,
        "Far West",         1,
        "Inside",           1,
        "North",            2,
        "Outside",          1,
        "South",            2,
        "West",             2,
    ] ),
}

