#!/usr/bin/env python

from BMovieConstants import *
from WeightedTuple import WeightedTuple


placeWordLists = {

    namePlaceModifier : WeightedTuple( [
        "Central",                  1,
        "Darkest",                  1,
        "Deepest",                  1,
        "Depths of",                1,
        "Inner",                    1,
        "Lower",                    1,
        "Outer",                    1,
        "The Bottom of",            1,
        "The Depths of",            1,
        "The Edge of",              1,
        "The Furthest Reaches of",  1,
        "The Inside of",            1,
        "The Outside of",           1,
        "The Top of",               1,
        "Upper",                    1,
    ] ),

    namePlaceArchitectureSingular : WeightedTuple( [
        "Castle",           2,
        "Cathedral",        1,
        "Cemetary",         1,
        "Circus",           1,
        "Crypt",            1,
        "Dungeon",          1,
        "Fortress",         2,
        "Inner Sanctum",    1,
        "Mausoleum",        1,
        "Palace",           2,
        "Stronghold",       2,
        "Temple",           2,
        "Tower",            2,
    ] ),

    namePlaceArchitecturePlural : WeightedTuple( [
        "Castles",          2,
        "Cathedrals",       1,
        "Dungeons",         1,
        "Palaces",          2,
        "Temples",          2,
        "Towers",           2,
    ] ),

    namePlaceTerritorySingular : WeightedTuple( [
        "City",             1,
        "Empire",           1,
        "Kingdom",          1,
        "Republic",         1,
        "Territory",        1,
        "City-State",       1,
    ] ),

    namePlaceTerritoryPlural : WeightedTuple( [
        "Cities",           1,
        "Empires",          1,
        "Kingdoms",         1,
        "Republics",        1,
        "Territories",      1,
        "City-States",      1,
    ] ),

    namePlaceGeographySingular : WeightedTuple( [
        "Cave",             1,
        "Cavern",           1,
        "Continent",        1,
        "Desert",           1,
        "Dimension",        1,
        "Forest",           1,
        "Galaxy",           1,
        "Jungle",           1,
        "Land",             1,
        "March",            1,
        "Marsh",            1,
        "Mountain",         1,
        "Netherworld",      1,
        "Ocean",            1,
        "Plain",            1,
        "Planet",           1,
        "Sea",              1,
        "Swamp",            1,
        "Underworld",       1,
        "Universe",         1,
        "Volcano",          1,
        "Wasteland",        1,
    ] ),

    namePlaceGeographyPlural : WeightedTuple( [
        "Caverns",          1,
        "Caves",            1,
        "Deserts",          1,
        "Dimensions",       1,
        "Forests",          1,
        "Galaxies",         1,
        "Jungles",          1,
        "Lands",            1,
        "Marches",          1,
        "Marshes",          1,
        "Mountains",        1,
        "Oceans",           1,
        "Plains",           1,
        "Planets",          1,
        "Seas",             1,
        "Swamps",           1,
        "Wastelands",       1,
    ] ),

    namePlaceCommon : WeightedTuple( [
        namePlaceArchitecturePlural,    1,
        namePlaceArchitectureSingular,  1,
        namePlaceGeographyPlural,       2,
        namePlaceGeographySingular,     2,
        namePlaceTerritoryPlural,       1,
        namePlaceTerritorySingular,     2,
    ] ),

    namePlaceProper : WeightedTuple( [
        namePlaceProperSimple,                                          6,
        [ namePlaceModifier, namePlaceProperSimple ],                   2,
        [ 'The', namePlaceProperArticle ],                              6,
        [ 'The', adjectivePlace, namePlaceCommon ],                     4,
        [ 'The', adjectivePlace, namePlaceProperArticle ],              4,
        [ 'The', namePlaceCommon, 'of', nameConcept ],                  2,
        [ 'The', namePlaceCommon, 'of', namePlaceProperSimple ],        1,
        [ 'The', namePlaceCommon, 'of The', namePlaceProperArticle ],   1,
    ] ),

    namePlaceProperSimple : WeightedTuple( (
        "Africa",
        "Aldebaran",
        "Altair",
        "America",
        "Andromeda",
        "Antarctica",
        "Antares",
        "Arcturus",
        "Asia",
        "Athens",
        "Atlantis",
        "Babylon",
        "Baghdad",
        "Beijing",
        "Betelgeuse",
        "Camelot",
        "China",
        "Deep Space",
        "Djibouti",
        "Earth",
        "Egypt",
        "Europe",
        "India",
        "Inner Space",
        "Japan",
        "Jupiter",
        "London",
        "Los Angeles",
        "Marathon",
        "Mars",
        "Mercury",
        "Mount Everest",
        "Navarone",
        "Neptune",
        "New York",
        "Orion",
        "Outer Space",
        "Paris",
        "Planet X",
        "Pluto",
        "Poughkeepsie",
        "Prehistoric Times",
        "Rigel",
        "Russia",
        "Saturn",
        "Sirius",
        "Space",
        "Stonehenge",
        "Texas",
        "Timbuktu",
        "Tokyo",
        "Uranus",
        "Vega",
        "Venus",
        "Washington",
        "Wongo Wongo",
     ) ),

    namePlaceProperArticle : WeightedTuple( [
        "Amazon",                           2,
        "Andes",                            1,
        "Andromeda Galaxy",                 1,
        "Beginning of Time",                2,
        "Burmuda Triangle",                 1,
        "Congo",                            1,
        "Distant Future",                   1,
        "Distant Past",                     1,
        "Eighth Dimension",                 1,
        "Eighth Planet",                    1,
        "Eleventh Planet",                  1,
        "End of Time",                      2,
        "Fifth Dimension",                  1,
        "Fourth Dimension",                 1,
        "Future",                           2,
        "Himalayas",                        1,
        "Jungle",                           1,
        "Land Before Time",                 1,
        "Land of Oz",                       1,
        "Lost World",                       2,
        "Marianas Trench",                  1,
        "Milky Way",                        1,
        "Moon",                             1,
        "New World",                        1,
        "Ninth Dimension",                  1,
        "Ninth Planet",                     1,
        "North Pole",                       1,
        "Occident",                         1,
        "OK Corral",                        1,
        "Old World",                        1,
        "Orient",                           1,
        "Outback",                          1,
        "Past",                             2,
        "Pleiades",                         1,
        "River Kwai",                       1,
        "Sargasso Sea",                     1,
        "Seven Seas",                       3,
        "Seventh Dimension",                1,
        "Sixth Dimension",                  1,
        "South Pole",                       3,
        "Tenth Planet",                     1,
        "Thirteenth Planet",                1,
        "Twelfth Planet",                   1,
        "Wild West",                        3,
        [ "City of", nameConcept ],         1,
        [ "Forest of", nameConcept ],       1,
        [ "Island of", nameConcept ],       1,
        [ "Lost City of", nameConcept ],    1,
        [ "Mountain of", nameConcept ],     1,
        [ "Mountains of", nameConcept ],    1,
        [ "Ocean of", nameConcept ],        1,
        [ "River of", nameConcept ],        1,
    ] ),
}

