#!/usr/bin/env python

from BMovieConstants import *
from WeightedTuple import WeightedTuple


eventWordLists = {

    nameEventSingularNeutral : WeightedTuple( [
        "Case",             1,
        "Day",              3,
        "Destiny",          2,
        "Game",             1,
        "Journey",          3,
        "Night",            2,
        "Trial",            1,
    ] ),

    nameEventSingularPositive : WeightedTuple( [
        "Dance",            1,
        "Feast",            1,
        "Liberation",       1,
        "Rise",             1,
        "Redemption",       1,
        "Triumph",          2,
        "Victory",          2,
    ] ),

    nameEventSingularNegative : WeightedTuple( [
        "Abduction",        1,
        "Assassination",    1,
        "Attack",           2,
        "Battle",           2,
        "Conquest",         2,
        "Conspiracy",       2,
        "Curse",            2,
        "Debacle",          1,
        "Destruction",      2,
        "Disappearance",    2,
        "Disaster",         2,
        "Downfall",         2,
        "Fall",             2,
        "Invasion",         3,
        "Murder",           1,
        "Mystery",          1,
        "Peril",            1,
        "Revenge",          2,
        "Storm",            1,
        "Strife",           1,
        "Tempest",          1,
        "Tragedy",          1,
        "Tribulation",      1,
        "War",              2,
    ] ),

    nameEventSingular : WeightedTuple( [
        nameEventSingularNeutral,   3,
        nameEventSingularPositive,  3,
        nameEventSingularNegative,  1,
    ] ),

    nameEventEpoch : WeightedTuple ( [
        "Century",          1,
        "Day",              6,
        "Decade",           1,
        "Eon",              1,
        "Epoch",            2,
        "Era",              3,
        "Millennium",       1,
        "Night",            6,
        "Month",            2,
        "Time",             6,
        "Week",             3,
        "Year",             3,
        "Summer",           1,
        "Winter",           1,
        "Springtime",       1,
        "Autumn",           1,
    ] ),

    nameEventStorySingular : WeightedTuple( [
        "Adventure",        1,
        "Dream",            1,
        "Epic",             1,
        "Fable",            1,
        "History",          2,
        "Legend",           3,
        "Mystery",          2,
        "Myth",             1,
        "Nightmare",        1,
        "Odyssey",          1,
        "Saga",             2,
        "Song",             1,
        "Scenario",         1,
        "Story",            2,
        "Tale",             2,
        "Trilogy",          1,
    ] ),

    nameEventStoryPlural : WeightedTuple( [
        "Adventures",       2,
        "Dreams",           1,
        "Fables",           1,
        "Legends",          2,
        "Mysteries",        1,
        "Myths",            1,
        "Nightmare",        2,
        "Songs",            1,
        "Stories",          2,
        "Tales",            2,
    ] ),

    nameEventPlural : WeightedTuple ( [
        "Adventures",       2,
        "Battles",          1,
        "Conquests",        1,
        "Curses",           1,
        "Days",             1,
        "Destruction",      1,
        "Games",            1,
        "Invasions",        1,
        "Journeys",         1,
        "Legends",          2,
        "Mysteries",        2,
        "Night",            1,
        "Perils",           1,
        "Stories",          1,
        "Storms",           1,
        "Tempests",         1,
        "Trials",           1,
        "Tribulations",     1,
        "Triumphs",         1,
        "Victories",        1,
        "Wars",             1,
    ] ),
}

